server:
  port: 8886

spring:
  data:
    redis:
      port: 6379
      host: redis
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/pblog_vue_springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 10
      max-active: 100

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.pblog.pojo
  mapper-locations: classpath:mapper/*.xml